- name: Test if `fail2ban_config_files` is set correctly
  assert:
    that:
      - fail2ban_config_files is defined
      - fail2ban_config_files is iterable
    quiet: true

- name: Test if `fail2ban_config_files` structure is correct
  assert:
    that:
      - item.src is defined
      - item.src is string
      - item.dest is defined
      - item.dest is string
    quiet: true
  loop: "{{ fail2ban_config_files }}"
  loop_control:
    label: "{{ item.src }}"
  when:
    - fail2ban_config_files is defined
    - fail2ban_config_files is iterable
